"""`0005_plan_d` against the models it migrates for (DEC-341's drift check, for Plan D's two tables).

The same approach as `test_scheduling_migration.py`: upgrade an empty SQLite database to head and ask
`compare_metadata` what it would still change for `model_decision` and `erasure_progress`. The
timestamp-with-time-zone half of DEC-339 needs a real Postgres server and is asserted in
`tests/unit/test_postgres_metadata.py`.
"""

from __future__ import annotations

from argparse import Namespace
from pathlib import Path
from typing import Any

import pytest
from alembic import command
from alembic.autogenerate import compare_metadata
from alembic.config import Config
from alembic.migration import MigrationContext
from sqlalchemy import Engine, Index, Table, create_engine, text
from sqlalchemy.exc import IntegrityError
from sqlmodel import SQLModel

from engine.approvals import MODEL_DECISION_TABLE, ModelDecisionRow
from engine.platform_db import PLATFORM_TABLES
from engine.privacy.tables import ERASURE_PROGRESS_TABLE, ErasureProgressRow
from tests.fixtures.postgres import alembic_upgrade

_ = (ModelDecisionRow, ErasureProgressRow)  # imported to register the tables with the metadata

OURS: frozenset[str] = frozenset({MODEL_DECISION_TABLE, ERASURE_PROGRESS_TABLE})
REPO_ROOT: Path = Path(__file__).resolve().parents[3]


def _table_of(item: Any) -> str | None:
    if isinstance(item, list):
        item = item[0]
    if not isinstance(item, tuple):
        return None
    for part in item:
        if isinstance(part, Index) and part.table is not None:
            return str(part.table.name)
        if isinstance(part, Table):
            return str(part.name)
    return next((part for part in item if isinstance(part, str) and part in OURS), None)


def drift(engine: Engine) -> list[Any]:
    with engine.connect() as connection:
        context = MigrationContext.configure(connection, opts={"compare_type": True})
        differences = compare_metadata(context, SQLModel.metadata)
    return [item for item in differences if _table_of(item) in OURS]


@pytest.fixture
def head(tmp_path: Path) -> Engine:
    path = tmp_path / "head.db"
    alembic_upgrade(f"sqlite:///{path}")
    return create_engine(f"sqlite:///{path}")


def test_the_plan_d_tables_are_declared() -> None:
    assert set(PLATFORM_TABLES) >= OURS


def test_0005_matches_the_models(head: Engine) -> None:
    try:
        assert drift(head) == []
    finally:
        head.dispose()


def test_one_progress_row_per_request_and_store(head: Engine) -> None:
    row = (
        "INSERT INTO erasure_progress (request_id, store, status, files_total, files_done, attempts, updated_at) "
        "VALUES ('er_1', 'uploads', 'pending', 1, 0, 0, '2026-09-23 10:00:00')"
    )
    try:
        with head.begin() as connection:
            connection.execute(text(row))
        with pytest.raises(IntegrityError), head.begin() as connection:
            connection.execute(text(row))
    finally:
        head.dispose()


def test_0005_downgrades_to_0004(tmp_path: Path) -> None:
    path = tmp_path / "down.db"
    config = Config(str(REPO_ROOT / "alembic.ini"), cmd_opts=Namespace(x=[f"url=sqlite:///{path}"]))
    config.set_main_option("script_location", str(REPO_ROOT / "alembic"))
    command.upgrade(config, "0005")
    command.downgrade(config, "0004")
    engine = create_engine(f"sqlite:///{path}")
    try:
        with engine.connect() as connection:
            names = {row[0] for row in connection.execute(text("SELECT name FROM sqlite_master"))}
        assert names & OURS == set()
        assert "alert" in names, "0004's tables stay"
    finally:
        engine.dispose()


def test_autogenerate_sees_every_platform_table_and_finds_nothing_to_do(tmp_path: Path) -> None:
    """`alembic check` - what `make revision` runs first - over a database migrated to head (DEC-888).

    `env.py` admits the registry's and the platform's tables and imports every model behind them, so
    a head database has nothing to add and, crucially, nothing to drop: a table the filter admitted
    without its model imported would come back as a `remove_table`.
    """
    path = tmp_path / "check.db"
    config = Config(str(REPO_ROOT / "alembic.ini"), cmd_opts=Namespace(x=[f"url=sqlite:///{path}"]))
    config.set_main_option("script_location", str(REPO_ROOT / "alembic"))
    command.upgrade(config, "head")
    command.check(config)  # raises AutoGenerateDiffsDetected on any difference
