"""Generate `docs/pilot/DATA_REQUEST.md` and `docs/pilot/templates/*_template.csv` (Plan E M59).

The committed files are the pilot's default request (telco churn, then win-back with a control
group). Like `templates/` (DEC-014) they are generated, committed and drift-checked: `--check`
writes nothing and exits 1 on drift, which is what `make pilot-check` and
`tests/unit/pilot/test_data_request.py` run. `--use-case` renders a request for other use cases to
any `--out` directory, for a client whose pilot is not the default one.
"""

from __future__ import annotations

import argparse
import difflib
import sys
from collections.abc import Sequence
from pathlib import Path

from engine.pilot.data_request import (
    build_data_request,
    load_wording,
    render_markdown,
    render_role_template,
    template_filename,
)

COMMAND: str = "python -m scripts.gen_data_request"
DEFAULT_OUT: Path = Path("docs/pilot")
REQUEST_FILENAME: str = "DATA_REQUEST.md"


def rendered_files(
    out_dir: Path, *, use_cases: tuple[str, ...] | None = None, root: Path | None = None
) -> list[tuple[Path, str]]:
    """Every file of the kit and its text: the request, then one template per requested table."""
    wording = load_wording(root)
    request = build_data_request(use_cases, root)
    files = [(out_dir / REQUEST_FILENAME, render_markdown(request, wording))]
    files += [
        (out_dir / "templates" / template_filename(table.role, wording), render_role_template(table))
        for table in request.tables
    ]
    return files


def write_kit(
    out_dir: Path,
    *,
    use_cases: tuple[str, ...] | None = None,
    root: Path | None = None,
    check: bool = False,
) -> int:
    """Write (or, with `check`, diff) the kit; returns the process exit code."""
    rendered = rendered_files(out_dir, use_cases=use_cases, root=root)
    if not check:
        for path, body in rendered:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(body, encoding="utf-8")
        return 0
    drifted = 0
    for path, body in rendered:
        current = path.read_text(encoding="utf-8") if path.is_file() else ""
        if current == body:
            continue
        drifted = 1
        sys.stdout.writelines(
            difflib.unified_diff(
                current.splitlines(keepends=True),
                body.splitlines(keepends=True),
                fromfile=str(path),
                tofile=f"{path} (generated by {COMMAND})",
            )
        )
    return drifted


def main(argv: Sequence[str] | None = None) -> int:
    parser = argparse.ArgumentParser(prog=COMMAND, description="Generate the pilot's data request kit.")
    parser.add_argument(
        "--out", type=Path, default=DEFAULT_OUT, help="directory to write (default: docs/pilot/)"
    )
    parser.add_argument(
        "--use-case",
        action="append",
        dest="use_cases",
        default=None,
        help="use case id to request data for; repeat for several (default: the pilot's two)",
    )
    parser.add_argument(
        "--configs", type=Path, default=None, help="configuration root (default: configs/ of this checkout)"
    )
    parser.add_argument("--check", action="store_true", help="write nothing; diff and exit 1 on drift")
    args = parser.parse_args(argv)
    use_cases = tuple(args.use_cases) if args.use_cases else None
    return write_kit(args.out, use_cases=use_cases, root=args.configs, check=args.check)


if __name__ == "__main__":  # pragma: no cover
    raise SystemExit(main())
