"""Generate `templates/<stem>_template.csv` and `templates/<stem>_template_README.md` from the configs.

The generated files are committed (DEC-014); `--check` writes nothing and exits 1 on drift, which is
what `make check-generated` and `tests/unit/test_generated_files.py` run.
"""

from __future__ import annotations

import argparse
import difflib
import sys
from collections.abc import Sequence
from pathlib import Path

from engine.config import list_use_case_ids, load_use_case
from engine.templates import render_template_csv, render_template_readme, template_filenames

COMMAND: str = "python -m scripts.gen_templates"
DEFAULT_OUT: Path = Path("templates")


def write_templates(out_dir: Path, *, root: Path | None = None, check: bool = False) -> int:
    """Render both files for every use case; return the process exit code.

    `check=False` writes them (creating `out_dir`) and returns 0. `check=True` writes nothing, prints
    a unified diff per differing or missing file and returns 1 when anything differs, else 0.
    """
    rendered: list[tuple[Path, str]] = []
    for use_case_id in list_use_case_ids(root):
        config = load_use_case(use_case_id, root)
        csv_name, readme_name = template_filenames(config)
        rendered.append((out_dir / csv_name, render_template_csv(config)))
        rendered.append((out_dir / readme_name, render_template_readme(config)))
    if not check:
        out_dir.mkdir(parents=True, exist_ok=True)
        for path, body in rendered:
            path.write_text(body, encoding="utf-8")
        return 0
    drifted = 0
    for path, body in rendered:
        current = path.read_text(encoding="utf-8") if path.is_file() else ""
        if current == body:
            continue
        drifted = 1
        sys.stdout.writelines(
            difflib.unified_diff(
                current.splitlines(keepends=True),
                body.splitlines(keepends=True),
                fromfile=str(path),
                tofile=f"{path} (generated by {COMMAND})",
            )
        )
    return drifted


def main(argv: Sequence[str] | None = None) -> int:
    """`--out templates/` (default), `--configs <root>` and `--check`; returns the process exit code."""
    parser = argparse.ArgumentParser(
        prog=COMMAND, description="Generate the upload templates from configs/use_cases/."
    )
    parser.add_argument(
        "--out", type=Path, default=DEFAULT_OUT, help="directory to write (default: templates/)"
    )
    parser.add_argument(
        "--configs", type=Path, default=None, help="configuration root (default: configs/ of this checkout)"
    )
    parser.add_argument("--check", action="store_true", help="write nothing; diff and exit 1 on drift")
    args = parser.parse_args(argv)
    out_dir: Path = args.out
    root: Path | None = args.configs
    return write_templates(out_dir, root=root, check=args.check)


if __name__ == "__main__":  # pragma: no cover
    raise SystemExit(main())
