"""What a run cost, from a published rate card - or nothing at all, said plainly.

`RunManifest.cost_estimate` has been in the contracts since Phase 1 and has always been filled with
`estimated_usd=None`, because a laptop is not billed and plan section 13.3 forbids writing a number
nobody measured. A SageMaker job *is* billed, so the number becomes writable - and the same rule
decides how.

What can be measured here is **billable time**: AWS itself reports it, in
`DescribeTrainingJob.BillableTimeInSeconds`, and that is the only place `ComputeInfo.billable_seconds`
is ever filled from. What cannot be measured here is a **bill**. What this module has is a list
price: `configs/aws_prices.yaml`, generated by `scripts/fetch_aws_prices.py` from AWS's public price
list, carrying the offer version and the publication date of the rate card it read.

So the arithmetic is `billable seconds x instances x list rate`, and `CostEstimate.basis` says in
words that that is what it is, naming the rate, the offer version and the date. A list price ignores
savings plans, spot, free tier, tax and every negotiated discount, so the number is an *order of
magnitude for a rate card*, not an invoice line, and the basis is what keeps it from being read as
one (DEC-330).

Four things all produce `None` rather than a number, and `None` is never rounded to zero:

* no billable time - a processing job reports start and end times, which are wall clock, and wall
  clock is not what SageMaker bills (DEC-332);
* no rate for that instance type in that region;
* no rate card at all, because a checkout may not have one;
* a local run, which was not billed by anyone.

No boto3 import at module scope, per this package's rule (DEC-306) - in fact none at all: a price
list is a file, and reading it needs no client, no credentials and no account.
"""

from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path
from typing import TYPE_CHECKING, Any, Final

import yaml

from engine.contracts import ComputeInfo, CostEstimate
from engine.utils.logging import get_logger, log_failure

if TYPE_CHECKING:
    from collections.abc import Mapping

__all__ = [
    "COMPONENT_FOR_BACKEND",
    "LIST_PRICE_BASIS",
    "NOT_BILLED",
    "NO_BILLABLE_TIME",
    "NO_RATE",
    "NO_TABLE",
    "PRICES_FILENAME",
    "PROCESSING_COMPONENT",
    "SECONDS_PER_HOUR",
    "TRAINING_COMPONENT",
    "UNREPORTED_INSTANCE",
    "UNREPORTED_REGION",
    "InstanceRate",
    "PriceTable",
    "cost_estimate",
    "load_price_table",
    "local_cost_estimate",
    "price_table_path",
]

_LOGGER = get_logger(__name__)

PRICES_FILENAME: Final[str] = "aws_prices.yaml"
"""The generated rate card, inside the configuration root beside the use cases."""

SECONDS_PER_HOUR: Final[float] = 3600.0
"""Not chosen: the rate card is published per hour and an hour is 3600 seconds."""

TRAINING_COMPONENT: Final[str] = "training"
PROCESSING_COMPONENT: Final[str] = "processing"
"""The two SageMaker components this product runs; the keys `fetch_aws_prices` writes."""

COMPONENT_FOR_BACKEND: Final[Mapping[str, str]] = {
    "sagemaker-training": TRAINING_COMPONENT,
    "sagemaker-processing": PROCESSING_COMPONENT,
}
"""`ComputeInfo.backend` -> the rate card component it is billed under. A backend that is not here
is not a SageMaker job, so it has no list price and gets `None`."""

NO_TABLE: Final[str] = (
    "No AWS price list is installed, so no list price could be applied. "
    "Regenerate configs/aws_prices.yaml with `make prices` to get an estimate."
)
NO_BILLABLE_TIME: Final[str] = (
    "SageMaker reported no billable time for this job, so no list price could be applied. "
    "A processing job reports wall-clock start and end times, which are not what is billed."
)
NO_RATE: Final[str] = (
    "The installed AWS price list has no published {component} rate for {instance_type} in "
    "{region}, so no list price could be applied."
)
UNREPORTED_INSTANCE: Final[str] = "an instance type the platform did not report"
UNREPORTED_REGION: Final[str] = "a region the platform did not report"
"""What `NO_RATE` names when the *lookup key* is missing rather than the rate.

A backend that did not say what it ran on cannot be priced, and the sentence has to say that rather
than borrow the "no billable time" one, which would be a false statement about a job whose billable
time was reported (DEC-330).
"""

NOT_BILLED: Final[str] = (
    "This run was not carried by a service that bills for it, so nothing was billed and there is "
    "no rate to apply."
)
"""Why `estimated_usd` is null, in the four cases where it is. Each names the missing thing."""

LIST_PRICE_BASIS: Final[str] = (
    "{billable_seconds:.0f} billable seconds reported by {source} x {instance_count} "
    "{instance_type} instance(s) at the AWS published list price for SageMaker {component} in "
    "{region}, USD {usd_per_hour} per hour (offer version {offer_version}, published "
    "{publication_date}). A published list price is not a bill: it ignores savings plans, spot, "
    "free tier, tax and any negotiated discount."
)
"""The sentence `CostEstimate.basis` carries when a number *was* written.

Every placeholder is filled from something that was reported or published - the seconds by AWS, the
rate and its provenance by the price list - so there is no slot in it for a number this product made
up (DEC-330).
"""


@dataclass(frozen=True, slots=True)
class InstanceRate:
    """One published hourly rate, with the provenance that makes it quotable."""

    component: str
    instance_type: str
    region: str
    usd_per_hour: float
    offer_version: str
    publication_date: str
    source_url: str


@dataclass(frozen=True, slots=True)
class PriceTable:
    """`configs/aws_prices.yaml`, parsed. Read-only, and missing entries are missing, not zero."""

    fetched_at: str
    currency: str
    unit: str
    rates: Mapping[str, Mapping[str, Mapping[str, float]]]
    """region -> component -> instance type -> USD per unit."""

    provenance: Mapping[str, Mapping[str, str]]
    """region -> {source_url, offer_version, publication_date}."""

    def rate(self, *, component: str, instance_type: str, region: str) -> InstanceRate | None:
        """The published rate, or `None` when this table does not carry one for that combination."""
        usd = self.rates.get(region, {}).get(component, {}).get(instance_type)
        if usd is None:
            return None
        source = self.provenance.get(region, {})
        return InstanceRate(
            component=component,
            instance_type=instance_type,
            region=region,
            usd_per_hour=usd,
            offer_version=source.get("offer_version", ""),
            publication_date=source.get("publication_date", ""),
            source_url=source.get("source_url", ""),
        )


def price_table_path(config_dir: Path | None = None) -> Path:
    """Where the rate card lives: `aws_prices.yaml` inside the configuration root."""
    # A deliberate local import: `engine.config` resolves the root from the environment and this
    # module is imported by things that have already decided what their root is.
    from engine.config import config_root

    return config_root(config_dir) / PRICES_FILENAME


def load_price_table(path: Path | None = None) -> PriceTable | None:
    """The installed rate card, or `None` when there is none to install.

    `None` rather than an exception, and `None` rather than an empty table: a checkout without a
    price list is a normal checkout, every caller has to handle "no rate" anyway, and the two
    answers - "I have no table" and "the table has no rate for this" - end up in different `basis`
    sentences, so they are kept apart here rather than merged into a lie that reads the same.
    """
    location = price_table_path() if path is None else path
    if not location.is_file():
        return None
    try:
        raw = yaml.safe_load(location.read_text(encoding="utf-8"))
    except (OSError, yaml.YAMLError) as exc:
        # A malformed rate card is a file this process was handed, not a reason to fail a run: the
        # cost is an annotation on the manifest and the run is the thing that matters (DEC-333).
        log_failure(_LOGGER, "prices.load", exc)
        return None
    if not isinstance(raw, dict):
        return None
    regions = raw.get("regions")
    rates: dict[str, dict[str, dict[str, float]]] = {}
    provenance: dict[str, dict[str, str]] = {}
    if isinstance(regions, dict):
        for region, document in regions.items():
            if not isinstance(document, dict):
                continue
            rates[str(region)] = _components(document.get("components"))
            provenance[str(region)] = {
                name: str(document.get(name, ""))
                for name in ("source_url", "offer_version", "publication_date")
            }
    return PriceTable(
        fetched_at=str(raw.get("fetched_at", "")),
        currency=str(raw.get("currency", "")),
        unit=str(raw.get("unit", "")),
        rates=rates,
        provenance=provenance,
    )


def _components(raw: Any) -> dict[str, dict[str, float]]:
    """One region's `components:` block, with anything that is not a number left out."""
    out: dict[str, dict[str, float]] = {}
    if not isinstance(raw, dict):
        return out
    for component, entries in raw.items():
        if not isinstance(entries, dict):
            continue
        out[str(component)] = {
            str(instance_type): float(price)
            for instance_type, price in entries.items()
            if isinstance(price, (int, float)) and not isinstance(price, bool)
        }
    return out


def local_cost_estimate(compute_seconds: float, *, basis: str) -> CostEstimate:
    """The estimate for a run nothing billed for: the seconds, a null price, and why (plan 13.3)."""
    return CostEstimate(compute_seconds=round(compute_seconds, 3), estimated_usd=None, basis=basis)


def cost_estimate(
    compute: ComputeInfo, *, table: PriceTable | None, compute_seconds: float | None = None
) -> CostEstimate:
    """What the run `compute` describes cost, at a published list price, or `None` and the reason.

    `compute_seconds` keeps whatever the pipeline already measured - the sum of its stage durations
    - because that is a real measurement of this run and the platform's wall clock is a different
    one. When it is not given, the platform's wall clock is used instead; when there is neither,
    the field is zero, which is the one number here that *is* a measurement: no seconds were
    recorded.

    The multiplication follows AWS's own instruction for `BillableTimeInSeconds`: it is the billable
    time of one instance, so the compute time billed for the job is that multiplied by the instance
    count.
    """
    seconds = _seconds(compute, compute_seconds)
    component = COMPONENT_FOR_BACKEND.get(compute.backend)
    if component is None:
        return local_cost_estimate(seconds, basis=NOT_BILLED)
    if table is None:
        return local_cost_estimate(seconds, basis=NO_TABLE)
    billable = compute.billable_seconds
    if billable is None:
        return local_cost_estimate(seconds, basis=NO_BILLABLE_TIME)
    if compute.instance_type is None or compute.region is None:
        # A different failure from the one above, and it has to read as one: the time was reported,
        # the *rate* cannot be looked up. Saying "no billable time" here would be untrue.
        return local_cost_estimate(
            seconds,
            basis=NO_RATE.format(
                component=component,
                instance_type=compute.instance_type or UNREPORTED_INSTANCE,
                region=compute.region or UNREPORTED_REGION,
            ),
        )
    rate = table.rate(component=component, instance_type=compute.instance_type, region=compute.region)
    if rate is None:
        return local_cost_estimate(
            seconds,
            basis=NO_RATE.format(
                component=component, instance_type=compute.instance_type, region=compute.region
            ),
        )
    instances = compute.instance_count or 1
    usd = billable * instances * rate.usd_per_hour / SECONDS_PER_HOUR
    return CostEstimate(
        compute_seconds=round(seconds, 3),
        estimated_usd=round(usd, 4),
        basis=LIST_PRICE_BASIS.format(
            billable_seconds=billable,
            source=compute.billable_seconds_source or "the compute service",
            instance_count=instances,
            instance_type=rate.instance_type,
            component=component,
            region=rate.region,
            usd_per_hour=rate.usd_per_hour,
            offer_version=rate.offer_version,
            publication_date=rate.publication_date,
        ),
    )


def _seconds(compute: ComputeInfo, measured: float | None) -> float:
    """The seconds `CostEstimate.compute_seconds` reports: what was measured, else the wall clock."""
    if measured is not None:
        return measured
    if compute.wall_clock_seconds is not None:
        return compute.wall_clock_seconds
    return 0.0
