"""`engine/aws/prices.py`: a published rate, or nothing - and never a zero standing in for nothing.

The rate card under test is the real one, `configs/aws_prices.yaml`, generated by
`scripts/fetch_aws_prices.py` from AWS's public price list. Reading the installed file rather than a
fixture is deliberate: the shape of that file is half the contract, and a fixture would let the
generator and the reader drift apart without a test noticing.

What the file is *not* is a source of expected numbers. No assertion below spells a dollar figure
out: each one recomputes it from the rate the table itself carries, so this module never becomes a
place where a price nobody sourced is written down (plan section 13.3).

The four `None` cases have a test each, and the reason they are four rather than one is that they
are four different sentences in `CostEstimate.basis`. "I have no table" and "the table has no rate
for this" send a reader to two different places, and merging them would produce a lie that reads
the same as the truth (DEC-330, DEC-333).
"""

from __future__ import annotations

from pathlib import Path

import pytest
import yaml

from engine.aws.prices import (
    LIST_PRICE_BASIS,
    NO_BILLABLE_TIME,
    NO_RATE,
    NO_TABLE,
    NOT_BILLED,
    PRICES_FILENAME,
    PROCESSING_COMPONENT,
    SECONDS_PER_HOUR,
    TRAINING_COMPONENT,
    UNREPORTED_INSTANCE,
    UNREPORTED_REGION,
    PriceTable,
    cost_estimate,
    load_price_table,
    local_cost_estimate,
    price_table_path,
)
from engine.aws.sagemaker_jobs import PROCESSING_BACKEND, TRAINING_BACKEND
from engine.contracts import ComputeInfo

REGION = "ap-south-1"
"""The one region the installed rate card carries; a test that needs "no rate" uses another."""


@pytest.fixture
def table(config_root: Path) -> PriceTable:
    loaded = load_price_table(config_root / PRICES_FILENAME)
    assert loaded is not None, "the generated rate card is missing from configs/"
    return loaded


def compute(**overrides: object) -> ComputeInfo:
    """A finished training job's `ComputeInfo`, with whatever this test wants changed."""
    values: dict[str, object] = {
        "backend": TRAINING_BACKEND,
        "job_name": "marketing-ai-train-r-1",
        "instance_type": "ml.m5.xlarge",
        "instance_count": 1,
        "region": REGION,
        "wall_clock_seconds": 300.0,
        "billable_seconds": 240.0,
        "billable_seconds_source": "DescribeTrainingJob.BillableTimeInSeconds",
    }
    values.update(overrides)
    return ComputeInfo(**values)  # type: ignore[arg-type]


# ---------------------------------------------------------------------------
# The installed rate card
# ---------------------------------------------------------------------------
def test_the_generated_file_is_where_the_reader_looks(config_root: Path) -> None:
    assert (config_root / PRICES_FILENAME).is_file()
    assert price_table_path(config_root) == config_root / PRICES_FILENAME


def test_the_table_carries_the_provenance_that_makes_a_rate_quotable(table: PriceTable) -> None:
    """A rate without an offer version and a date is a number, not a published price."""
    rate = table.rate(component=TRAINING_COMPONENT, instance_type="ml.m5.xlarge", region=REGION)

    assert rate is not None
    assert rate.usd_per_hour > 0
    assert rate.offer_version
    assert rate.publication_date
    assert rate.source_url.startswith("https://")
    assert table.currency == "USD"
    assert table.unit == "hour"


def test_both_components_this_product_runs_are_priced(table: PriceTable) -> None:
    for component in (TRAINING_COMPONENT, PROCESSING_COMPONENT):
        assert table.rate(component=component, instance_type="ml.m5.xlarge", region=REGION) is not None


def test_a_region_the_card_does_not_cover_has_no_rate(table: PriceTable) -> None:
    assert table.rate(component=TRAINING_COMPONENT, instance_type="ml.m5.xlarge", region="eu-west-1") is None


def test_an_instance_type_the_card_does_not_carry_has_no_rate(table: PriceTable) -> None:
    assert table.rate(component=TRAINING_COMPONENT, instance_type="ml.made.up", region=REGION) is None


def test_a_checkout_without_a_rate_card_is_a_normal_checkout(tmp_path: Path) -> None:
    assert load_price_table(tmp_path / "nothing.yaml") is None


def test_a_malformed_rate_card_is_not_a_reason_to_fail_a_run(tmp_path: Path) -> None:
    """The cost is an annotation on the manifest; the run is the thing that matters (DEC-333)."""
    broken = tmp_path / "aws_prices.yaml"
    broken.write_text("regions: [this is not a mapping\n", encoding="utf-8")
    assert load_price_table(broken) is None


def test_a_rate_that_is_not_a_number_is_left_out_rather_than_coerced(tmp_path: Path) -> None:
    path = tmp_path / "aws_prices.yaml"
    path.write_text(
        yaml.safe_dump(
            {
                "fetched_at": "2026-09-22",
                "currency": "USD",
                "unit": "hour",
                "regions": {
                    REGION: {
                        "source_url": "https://example.invalid",
                        "offer_version": "1",
                        "publication_date": "2026-09-21",
                        "components": {TRAINING_COMPONENT: {"ml.m5.xlarge": "free", "ml.m5.large": 0.121}},
                    }
                },
            }
        ),
        encoding="utf-8",
    )
    loaded = load_price_table(path)

    assert loaded is not None
    assert loaded.rate(component=TRAINING_COMPONENT, instance_type="ml.m5.xlarge", region=REGION) is None
    assert loaded.rate(component=TRAINING_COMPONENT, instance_type="ml.m5.large", region=REGION) is not None


# ---------------------------------------------------------------------------
# An estimate that can be stated
# ---------------------------------------------------------------------------
def test_billable_time_at_the_published_rate_is_the_whole_arithmetic(table: PriceTable) -> None:
    rate = table.rate(component=TRAINING_COMPONENT, instance_type="ml.m5.xlarge", region=REGION)
    assert rate is not None

    estimate = cost_estimate(compute(), table=table)

    expected = 240.0 * 1 * rate.usd_per_hour / SECONDS_PER_HOUR
    assert estimate.estimated_usd == pytest.approx(expected, rel=1e-9, abs=1e-4)


def test_the_instance_count_multiplies_the_billable_time(table: PriceTable) -> None:
    """AWS's own instruction: `BillableTimeInSeconds` is the billable time of *one* instance."""
    rate = table.rate(component=TRAINING_COMPONENT, instance_type="ml.m5.xlarge", region=REGION)
    assert rate is not None

    three = cost_estimate(compute(instance_count=3), table=table)

    expected = 240.0 * 3 * rate.usd_per_hour / SECONDS_PER_HOUR
    assert three.estimated_usd == pytest.approx(expected, rel=1e-9, abs=1e-4)
    assert "3 ml.m5.xlarge instance(s)" in three.basis


def test_the_basis_says_the_number_is_a_list_price_and_names_its_provenance(table: PriceTable) -> None:
    """A list price is not a bill, and `basis` is the field that keeps it from being read as one."""
    rate = table.rate(component=TRAINING_COMPONENT, instance_type="ml.m5.xlarge", region=REGION)
    assert rate is not None

    basis = cost_estimate(compute(), table=table).basis

    assert "list price" in basis
    assert str(rate.usd_per_hour) in basis
    assert rate.offer_version in basis
    assert rate.publication_date in basis
    assert "240 billable seconds" in basis
    assert "DescribeTrainingJob.BillableTimeInSeconds" in basis
    assert "savings plans" in basis and "spot" in basis


def test_the_basis_template_has_no_slot_for_an_invented_number() -> None:
    """Every placeholder is filled from something reported or published, and there are no others."""
    import string

    fields = {name for _, name, _, _ in string.Formatter().parse(LIST_PRICE_BASIS) if name}
    assert fields == {
        "billable_seconds",
        "source",
        "instance_count",
        "instance_type",
        "component",
        "region",
        "usd_per_hour",
        "offer_version",
        "publication_date",
    }


def test_the_seconds_the_pipeline_measured_are_the_seconds_reported(table: PriceTable) -> None:
    """The stage durations are a real measurement of this run; the platform's clock is another one."""
    estimate = cost_estimate(compute(), table=table, compute_seconds=17.25)
    assert estimate.compute_seconds == 17.25


def test_without_a_measurement_the_platforms_wall_clock_is_used(table: PriceTable) -> None:
    assert cost_estimate(compute(), table=table).compute_seconds == 300.0


def test_with_neither_the_seconds_are_zero_which_is_itself_a_measurement(table: PriceTable) -> None:
    """No seconds were recorded: that is a fact, unlike a fabricated price."""
    estimate = cost_estimate(compute(wall_clock_seconds=None), table=table)
    assert estimate.compute_seconds == 0.0


# ---------------------------------------------------------------------------
# The four ways there is no number to state
# ---------------------------------------------------------------------------
def test_no_rate_card_means_no_estimate_and_says_which_file_is_missing() -> None:
    estimate = cost_estimate(compute(), table=None)
    assert estimate.estimated_usd is None
    assert estimate.basis == NO_TABLE
    assert PRICES_FILENAME in estimate.basis


def test_a_job_with_no_billable_time_has_no_estimate(table: PriceTable) -> None:
    """A processing job reports wall clock, and wall clock is not what SageMaker bills (DEC-332)."""
    estimate = cost_estimate(
        compute(backend=PROCESSING_BACKEND, billable_seconds=None, billable_seconds_source=None),
        table=table,
    )
    assert estimate.estimated_usd is None
    assert estimate.basis == NO_BILLABLE_TIME


def test_an_instance_the_card_does_not_price_has_no_estimate_and_names_it(table: PriceTable) -> None:
    estimate = cost_estimate(compute(instance_type="ml.made.up"), table=table)

    assert estimate.estimated_usd is None
    assert estimate.basis == NO_RATE.format(
        component=TRAINING_COMPONENT, instance_type="ml.made.up", region=REGION
    )
    assert "ml.made.up" in estimate.basis and REGION in estimate.basis


def test_a_backend_that_did_not_say_what_it_ran_on_is_a_missing_rate_not_a_missing_time(
    table: PriceTable,
) -> None:
    """The time *was* reported; it is the lookup key that is absent, and the sentence must say so."""
    estimate = cost_estimate(compute(instance_type=None, region=None), table=table)

    assert estimate.estimated_usd is None
    assert estimate.basis != NO_BILLABLE_TIME
    assert UNREPORTED_INSTANCE in estimate.basis
    assert UNREPORTED_REGION in estimate.basis


def test_a_run_nothing_billed_for_has_no_estimate(table: PriceTable) -> None:
    """A fabricated zero is indistinguishable from a real measurement of free compute."""
    estimate = cost_estimate(compute(backend="thread"), table=table)

    assert estimate.estimated_usd is None
    assert estimate.basis == NOT_BILLED


@pytest.mark.parametrize(
    "broken",
    [
        {"backend": "thread"},
        {"instance_type": "ml.made.up"},
        {"billable_seconds": None, "billable_seconds_source": None},
        {"region": "eu-west-1"},
    ],
)
def test_no_path_through_this_module_ever_writes_a_zero(table: PriceTable, broken: dict[str, object]) -> None:
    """`None` is never rounded to zero, because a zero would read as a measurement."""
    estimate = cost_estimate(compute(**broken), table=table)
    assert estimate.estimated_usd is None


def test_a_local_run_reports_its_seconds_and_no_price() -> None:
    estimate = local_cost_estimate(3.14159, basis=NOT_BILLED)
    assert estimate.estimated_usd is None
    assert estimate.compute_seconds == 3.142
    assert estimate.basis == NOT_BILLED


def test_a_zero_second_job_is_still_priced_at_zero_dollars_only_if_aws_said_zero(
    table: PriceTable,
) -> None:
    """Zero billable seconds is a *reported* zero, so the arithmetic may honestly produce zero."""
    estimate = cost_estimate(compute(billable_seconds=0.0), table=table)
    assert estimate.estimated_usd == 0.0
    assert "0 billable seconds" in estimate.basis
